name: CI

on:
  push: { branches: [main] }
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: "rustfmt,clippy"

      - name: Check Formatting
        run: cargo fmt --all -- --check

      - name: Lint
        run: cargo clippy --release -- -D warnings

      - name: Build & Test
        run: cargo test